# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'Stories' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'AnimatedCollectionViewLayout'

  # Pods for Stories

  target 'StoriesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'StoriesUITests' do
    # Pods for testing
  end

end
